name: Deploy

on: [push, pull_request]

jobs:
  spin:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go test -v -race -coverpkg=./... ./...
